name: Build Justice APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '33'
        build-tools-version: '36.0.0'

    - name: Accept Android SDK licenses manually
      run: |
        mkdir -p $ANDROID_SDK_ROOT/licenses
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_SDK_ROOT/licenses/android-sdk-license
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" > $ANDROID_SDK_ROOT/licenses/android-sdk-preview-license

    - name: Install build dependencies
      run: |
        pip install buildozer cython

    - name: Build Justice APK
      run: buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: JusticeAI-debug.apk
        path: bin/*.apk
