name: Build Justice APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel \
          openjdk-11-jdk unzip zip libncurses5 libstdc++6 libffi-dev libssl-dev \
          build-essential git wget curl

    - name: Install Android SDK cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses
        yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Install Buildozer and dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install buildozer cython

    - name: Run Buildozer to build APK
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export ANDROID_NDK_HOME=$HOME/android-sdk/ndk-bundle
        buildozer -v android debug
